// <auto-generated />
namespace MVCPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idkwhatthisoneistruly : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idkwhatthisoneistruly));
        
        string IMigrationMetadata.Id
        {
            get { return "202305062154405_idk what this one is truly"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
